development:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: tapsell_development
  pool: 5
  username: 
  password:

test: &TEST
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: tapsell_test
  pool: 5
  username: 
  password:

production:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: tapsell_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST